config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :goals, only: [:new, :create, :show]
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :title, :user_id, presence: true

  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :email, :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token
  
  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def password=(pass)
    @password = pass
    self.password_digest = BCrypt::Password.create(pass)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.create(goal_params)

    if @goal.save
      redirect_to user_url(@goal.user_id)
    else
      flash.now[:errors] = @goals.errors.full_messages
      render :new
    end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  private

  def goal_params
    params.require(:goal).permit(:title, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if user
      user.reset_session_token!
      session[:session_token] = user.session_token
      redirect_to user_url(user)
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    user = User.find_by(session_token: session[:session_token])
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)

    if user.save
      session[:session_token] = user.session_token
      redirect_to user_url(user)
    else
      flash[:errors] = user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{ form_authenticity_token }'>".html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/goals/new.html.erb
<h1>Log in</h1>

<form action="<%= goals_url %>" method="post">
  <%= auth_token %>
  <label>Title
    <input type="text" name="goal[title]" value="">
  </label>

  <input type="hidden" name="goal[user_id]" value="<%= current_user.id %>">
  <input type="submit" value="Log in">
  
</form>

app/views/goals/show.html.erb
<h1>Goal <%= @goal.title %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%# if current_user %>
  <form action="<%= session_url %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Log out">
  </form>
<%# end  %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Create a new account</h1>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label>Email
    <input type="text" name="user[email]" value="">
  </label>

  <label>Password
    <input type="text" name="user[password]" value="">
  </label>

  <input type="submit" value="Log in">
</form>

app/views/users/show.html.erb
<p>Logged in as: <%= @user.email %></p>
<h1><%= @user.email %></h1>